import { ChakraLink } from '@/app/components/ChakraLink';
import { Heading, ListItem, Text, UnorderedList } from '@chakra-ui/react';

export default async function PrivacyPage() {
  return (
    <>
      <Heading as='h1' textColor='whiteAlpha.800'>
        Privacy Policy
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        Last Updated: 2024-08-04
      </Text>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        This Privacy Policy explains how eCom in Motion ("we", "us", "our")
        collects, uses, discloses, and safeguards your information when you use
        our services. Please read this Privacy Policy carefully. By using our
        services, you agree to the terms of this Privacy Policy.
      </Text>
      <Heading
        as='h2'
        fontSize='lg'
        textColor='whiteAlpha.800'
        fontWeight='600'
      >
        1. Information We Collect
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        We collect different types of information to provide and improve our
        services to you:
      </Text>
      <UnorderedList fontSize='lg' textColor='whiteAlpha.700'>
        <ListItem mb={3}>
          <b>Personal Information:</b> When you sign up for our services, we may
          collect personal information such as your name, email address, and
          payment information through Stripe for processing transactions.
        </ListItem>
        <ListItem mb={3}>
          <b>Usage Data:</b> We collect information about how you use our
          services. This includes your interactions with our website, searches,
          product ideas generated by our tools, and your interaction with our
          crawlers and APIs.
        </ListItem>
        <ListItem>
          <b>Device Information:</b> We may collect information about the device
          you use to access our services, including the device type, operating
          system, and browser type.
        </ListItem>
      </UnorderedList>
      <Heading
        as='h2'
        fontSize='lg'
        textColor='whiteAlpha.800'
        fontWeight='600'
      >
        2. How We Use Your Information
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        We use the collected information in various ways, including:
      </Text>
      <UnorderedList fontSize='lg' textColor='whiteAlpha.700'>
        <ListItem mb={3}>
          <b>To Provide and Maintain Services:</b> We use your information to
          deliver our services, including generating product ideas and pricing
          data, and to process your payments through Stripe.
        </ListItem>
        <ListItem mb={3}>
          <b>To Improve Our Services:</b> We analyze your usage data to improve
          and personalize our services.
        </ListItem>
        <ListItem>
          <b>To Communicate with You:</b> We may use your information to send
          you updates, support messages, or other notifications related to your
          account or our services.
        </ListItem>
        <ListItem>
          <b>To Ensure Security:</b> We use your information to detect and
          prevent fraud, unauthorized activities, and other harmful actions.
        </ListItem>
      </UnorderedList>
      <Heading
        as='h2'
        fontSize='lg'
        textColor='whiteAlpha.800'
        fontWeight='600'
      >
        3. How We Share Your Information
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        We may share your information with:
      </Text>
      <UnorderedList fontSize='lg' textColor='whiteAlpha.700'>
        <ListItem mb={3}>
          <b>Third-Party Service Providers:</b> We use third-party services like
          Stripe for payment processing and Supabase for database management.
          These providers have access to your personal information only to
          perform specific tasks on our behalf and are obligated not to disclose
          or use it for any other purpose.
        </ListItem>
        <ListItem mb={3}>
          <b>Legal Compliance:</b> We may disclose your information if required
          by law or in response to valid requests by public authorities (e.g., a
          court or government agency).
        </ListItem>
        <ListItem>
          <b>Business Transfers:</b> If we are involved in a merger,
          acquisition, or asset sale, your information may be transferred as
          part of that transaction.
        </ListItem>
      </UnorderedList>
      <Heading
        as='h2'
        fontSize='lg'
        textColor='whiteAlpha.800'
        fontWeight='600'
      >
        4. Security of Your Information
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        We use industry-standard security measures to protect your information.
        However, no method of transmission over the internet or method of
        electronic storage is 100% secure. We cannot guarantee absolute
        security.
      </Text>
      <Heading
        as='h2'
        fontSize='lg'
        textColor='whiteAlpha.800'
        fontWeight='600'
      >
        5. Your Data Protection Rights
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        Depending on your location, you may have the following rights regarding
        your personal information:
      </Text>
      <UnorderedList fontSize='lg' textColor='whiteAlpha.700'>
        <ListItem mb={3}>
          <b>Access:</b> You have the right to request copies of your personal
          information.
        </ListItem>
        <ListItem mb={3}>
          <b>Correction:</b> You have the right to request that we correct any
          information you believe is inaccurate or complete information you
          believe is incomplete.
        </ListItem>
        <ListItem mb={3}>
          <b>Deletion:</b> You have the right to request that we delete your
          personal information.
        </ListItem>
        <ListItem mb={3}>
          <b>Restrict Processing:</b> You have the right to request that we
          restrict the processing of your personal information.
        </ListItem>
        <ListItem mb={3}>
          <b>Object to Processing:</b> You have the right to object to our
          processing of your personal information.
        </ListItem>
        <ListItem>
          <b>Data Portability:</b> You have the right to request that we
          transfer your information to another organization, or directly to you.
        </ListItem>
      </UnorderedList>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        If you make a request, we have one month to respond to you. If you would
        like to exercise any of these rights, please contact us at{' '}
        <ChakraLink
          href='/contact'
          label='this page'
          color='blue.500'
          hover={true}
        />
        .
      </Text>
      <Heading
        as='h2'
        fontSize='lg'
        textColor='whiteAlpha.800'
        fontWeight='600'
      >
        6. Children's Privacy
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        Our services are not directed to children under 13, and we do not
        knowingly collect personal information from children under 13. If we
        become aware that we have inadvertently collected such information, we
        will take steps to delete it as soon as possible.
      </Text>
      <Heading
        as='h2'
        fontSize='lg'
        textColor='whiteAlpha.800'
        fontWeight='600'
      >
        7. Changes to This Privacy Policy
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        We may update our Privacy Policy from time to time. We will notify you
        of any changes by posting the new Privacy Policy on this page. You are
        advised to review this Privacy Policy periodically for any changes.
      </Text>
      <Heading
        as='h2'
        fontSize='lg'
        textColor='whiteAlpha.800'
        fontWeight='600'
      >
        8. Contact Us
      </Heading>
      <Text fontSize='lg' textColor='whiteAlpha.700'>
        If you have any questions about this Privacy Policy, please contact us
        at:
      </Text>
      <UnorderedList fontSize='lg' textColor='whiteAlpha.700'>
        <ListItem>
          <b>Email:</b>{' '}
          <ChakraLink
            href='/contact'
            label='Contact us'
            color='blue.500'
            hover={true}
          />
        </ListItem>
      </UnorderedList>
    </>
  );
}
