name: CI Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:slim

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun update
          bun install

      - name: Lint with eslint
        run: bun run lint

      - name: Run Nextjs build test
        run: bun run build
